;; Project specific Emacs settings
((nil . ((indent-tabs-mode . nil)
         (fill-column . 92)
         (show-trailing-whitespace . t)))
 (c-mode . ((c-file-style . "k&r")
            (c-basic-offset . 4)))
 (c++-mode . ((c-file-style . "stroustrup")
              (c-basic-offset . 4)
              (c-file-offsets . ((innamespace . 0)
                                 (label . *)
                                 (substatement-label . *)
                                 (case-label . +)
                                 (inline-open . 0)
                                 (inlambda . 0))))))
