// This file is part of the Archon project, a suite of C++ libraries.
//
// Copyright (C) 2022 Kristian Spangsege <kristian.spangsege@gmail.com>
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this
// software and associated documentation files (the "Software"), to deal in the Software
// without restriction, including without limitation the rights to use, copy, modify, merge,
// publish, distribute, sublicense, and/or sell copies of the Software, and to permit
// persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or
// substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
// INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
// PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
// FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
// OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#ifndef ARCHON_X_IMAGE_X_ERROR_HPP
#define ARCHON_X_IMAGE_X_ERROR_HPP

/// \file


#include <string>
#include <system_error>

#include <archon/core/features.h>


namespace archon::image {


/// \brief Image errors.
///
/// These errors may be generated by functions such as \ref image::load().
///
/// \sa \ref image::make_error_code(image::Error)
///
enum class Error {
    /// Attempted use of unavailable file format. Use of an unavailable file format was
    /// attempted. See \ref image::FileFormat::is_available().
    file_format_unavailable = 1,

    /// Image is too large, or too small. The horizontal and/or vertical size of an image
    /// was too big, or too small. This error can be generated during a load operation (\ref
    /// image::try_load()) if the loaded image is too large, or during a save operation
    /// (\ref image::try_save()) if the saved image is too large, or too small. Most image
    /// file formats do not allow images of zero size.
    image_size_out_of_range = 2,

    /// Invalid image file format identifier. Generated by \ref image::load() and \ref
    /// image::save() if a file format identifier was specified (\ref
    /// image::LoadConfig::file_format), but there were no file formats associated with that
    /// identifier in the file format registry (\ref image::LoadConfig::registry).
    no_such_file_format = 3,

    /// File format could not be detected. Automatic detection of the file format failed
    /// because the file in question (file name extension, MIME type, leading bytes of file
    /// contents) did not match any of the known file formats. This error is principally
    /// generated by \ref image::try_load() and \ref image::try_save(), which is where
    /// automatic file format detection takes place.
    file_format_detection_failed = 4,

    /// File could not be loaded. The contents of the file is invalid or the file format is
    /// different from the assumed one. This error may also be generated in place of \ref
    /// loading_process_failed when an underlying file formal library does not offer a clean
    /// way to discriminate between errors caused by invalid file contents and other errors.
    bad_file = 5,

    /// Loading process failed. A failure occurred during the loading of an image, and the
    /// failure was not due to invalid file contents. This error can also be generated if a
    /// failure occurs during automatic file format detection (\ref
    /// image::FileFormat::try_recognize()). See also \ref bad_file.
    loading_process_failed = 6,

    /// Saving process failed. A failure of unspecified type occurred during the saving of
    /// an image.
    saving_process_failed = 7,
};


/// \brief Make image error code object.
///
/// This function constructs an image error code object. Together with the specialization of
/// `std::is_error_code_enum<T>` for \ref image::Error, this allows for implicit conversion
/// from an enumeration value to an error code object.
///
auto make_error_code(image::Error) noexcept -> std::error_code;








// Implementation


} // namespace archon::image

namespace std {


template<> class is_error_code_enum<archon::image::Error> {
public:
    static constexpr bool value = true;
};


} // namespace std

namespace archon::image {

namespace impl {


class ErrorCategory final
    : public std::error_category {
public:
    auto name() const noexcept -> const char* override;
    auto message(int) const -> std::string override;
};


inline constinit const impl::ErrorCategory g_error_category;


} // namespace impl


inline auto make_error_code(image::Error err) noexcept -> std::error_code
{
    return std::error_code(int(err), impl::g_error_category);
}


} // namespace archon::image

#endif // ARCHON_X_IMAGE_X_ERROR_HPP
