// This file is part of the Archon project, a suite of C++ libraries.
//
// Copyright (C) 2024 Kristian Spangsege <kristian.spangsege@gmail.com>
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this
// software and associated documentation files (the "Software"), to deal in the Software
// without restriction, including without limitation the rights to use, copy, modify, merge,
// publish, distribute, sublicense, and/or sell copies of the Software, and to permit
// persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or
// substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
// INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
// PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
// FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
// OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#ifndef ARCHON_X_DISPLAY_X_ERROR_HPP
#define ARCHON_X_DISPLAY_X_ERROR_HPP

/// \file


#include <system_error>


namespace archon::display {


/// \brief Display errors.
///
/// These errors may be generated by functinos such as \ref
/// display::Connection::try_new_window().
///
/// \sa \ref display::make_error_code(display::Error)
///
enum class Error {
    ///            
    display_uses_unsupported_pixel_format = 1,
};


/// \brief Make display error code object.
///
/// This function constructs a display error code object. Together with the specialization
/// of `std::is_error_code_enum<T>` for \ref display::Error, this allows for implicit
/// conversion from an enum value to an error code object.
///
auto make_error_code(display::Error) noexcept -> std::error_code;








// Implementation


} // namespace archon::display

namespace std {


template<> class is_error_code_enum<archon::display::Error> {
public:
    static constexpr bool value = true;
};


} // namespace std

namespace archon::display {

namespace impl {


class ErrorCategory
    : public std::error_category {
public:
    auto name() const noexcept -> const char* override final;
    auto message(int) const -> std::string override final;
};


inline constinit const impl::ErrorCategory g_error_category;


} // namespace impl


inline auto make_error_code(display::Error err) noexcept -> std::error_code
{
    return std::error_code(int(err), impl::g_error_category);
}


} // namespace archon::display

#endif // ARCHON_X_DISPLAY_X_ERROR_HPP
