// This file is part of the Archon project, a suite of C++ libraries.
//
// Copyright (C) 2020 Kristian Spangsege <kristian.spangsege@gmail.com>
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

#ifndef ARCHON_X_BASE_X_RANDOM_HPP
#define ARCHON_X_BASE_X_RANDOM_HPP

/// \file


#include <cstddef>
#include <cstdint>
#include <type_traits>
#include <iterator>
#include <initializer_list>
#include <array>
#include <utility>
#include <memory>
#include <random>
#include <algorithm>
#include <functional>
#include <stdexcept>
#include <vector>

#include <archon/base/features.h>
#include <archon/base/integer.hpp>
#include <archon/base/span.hpp>
#include <archon/base/buffer.hpp>


namespace archon::base {


/// \brief Seed a PRNG nondeterministically.
///
/// This function uses \ref seed_nondeterministically() to perform a
/// nondeterministic seeding of the specified pseudo random number generator.
///
/// Example:
///
/// \code{.cpp}
///
///   std::mt19937_64 random;
///   base::seed_prng_nondeterministically(random); // Throws
///   int x = std::uniform_int_distribution<int>(1, 1000)(random);
///
/// \endcode
///
/// \tparam E A pseudo random number generator. Currently, only variations over
/// `std::mersenne_twister_engine` are supported.
///
/// This function is thread-safe.
///
template<class E> void seed_prng_nondeterministically(E& engine);



/// \brief Provide nondeterministic seed sequence for PRNG.
///
/// This function constructs a seed sequence (\ref base::SeedSeq) from
/// nondeterministic input (to the extent possible on this platform) and passes
/// it as argument in an invocation of the specified function. The function is
/// expected to use the passed object for seeding a pseudo random number
/// generator.
///
/// This function makes an effort to provide enough entropy to fully saturate N
/// 32-bit seed values as generated by an invocation of \ref
/// base::SeedSeq::generate(), where N is the value of \p num_seed_words. If
/// that is not possible, this function makes an effort to provide as much
/// entropy as possible.
///
/// The specified function will be invoked as if by the following code:
///
/// \code{.cpp}
///
///   func(seed_seq); // Throws
///
/// \endcode
///
/// Here, `seed_seq` is a non-const instance of \ref base::SeedSeq.
///
template<std::size_t num_seed_words, class F> inline void seed_nondeterministically(F func);



/// \brief Provide nondeterministic seed sequence for PRNG.
///
/// This function is equivalent to \ref seed_nondeterministically(), but allows
/// for the number of seed words to not be known at compile time. The cost is
/// one dynamic allocation.
///
template<class F> inline void seed_nondeterministically_a(std::size_t num_seed_words, F func);



/// \brief Provide good quality seeding for random number generators.
///
/// This class offers a way to produce a reasonably well-behaved sequence of
/// 32-bit integers from a potentially poorly distributed or strongly biased
/// initial seed sequence. The produced sequence (\ref generate()) will be
/// rectangularly distributed over the entire 32-bit range. For optimum results,
/// the initial seed sequence should contain enough entropy to saturate all the
/// generated integers. For example, if N integers are generated, the initial
/// seed sequence should contain at least N times 32 bits of entropy.
///
/// This class provides the same functionality as `std::seed_seq`, but adds the
/// ability to refer to an externally owned initial seed sequence (\ref
/// no_copy()). Use this to avoid dynamic allocation.
///
/// Just like `std::seed_seq`, this class meets the *seed sequence* requirements
/// as defined by C++17 section 29.6.1.2.
///
/// The \ref generate() function is implemented using exactly the same algorithm
/// as is required for `std::seed_seq::generate()`.
///
class SeedSeq {
public:
    using result_type = std::uint_least32_t;

    /// \brief Avoid copying the initial seed sequence.
    ///
    /// In contrast to a seed sequence object created by one of the (standard)
    /// constructors of this class, a seed sequence object produced by this
    /// function does not contain a copy of the specified initial seed
    /// sequence. It instead contains a copy of the specified memory reference
    /// (\p init_seed_seq), so the caller must ensure that the referenced memory
    /// stays alive for as long as the returned seed sequence object is in
    /// use. The upside is that no memory needs to be allocated in order to hold
    /// a copy of the initial seed sequence.
    ///
    static SeedSeq no_copy(base::Span<const result_type> init_seed_seq) noexcept;

    SeedSeq() noexcept = default;
    template<class T> SeedSeq(std::initializer_list<T> init_seed_seq);
    template<class I> SeedSeq(I begin, I end);

    template<class I> void generate(I begin, I end) const;

    std::size_t size() const noexcept;
    template<class I> void param(I dest) const;

    SeedSeq(SeedSeq&&) noexcept = default;
    SeedSeq& operator=(SeedSeq&&) noexcept = default;

private:
    std::unique_ptr<result_type[]> m_init_seed_seq_owner;
    base::Span<const result_type> m_init_seed_seq;

    template<class I> void init(I begin, I end);
};








// Implementation


namespace detail {


struct NondeterministicRandomSeeder {
    static constexpr std::size_t num_extra_entropy_words = 3;

    using input_word_type = std::random_device::result_type;
    using buffer_ref_type = base::Span<input_word_type>;
    using extra_entropy_type = std::array<input_word_type, num_extra_entropy_words>;

    template<class T, std::size_t w, std::size_t n, std::size_t m, std::size_t r, T a,
             std::size_t u, T d, std::size_t s, T b, std::size_t t, T c, std::size_t l, T f>
    static void seed_prng(std::mersenne_twister_engine<T, w, n, m, r, a, u, d, s, b, t, c, l, f>& engine)
    {
        constexpr std::size_t num_state_words = n;
        constexpr std::size_t state_word_size = w;
        constexpr std::size_t num_seed_words = get_num_seed_words(num_state_words, state_word_size); // Throws
        base::seed_nondeterministically<num_seed_words>([&](base::SeedSeq& seed_seq) {
            engine.seed(seed_seq); // Throws
        }); // Throws
    }

    static constexpr std::size_t get_num_seed_words(std::size_t num_state_words,
                                                    std::size_t state_word_size)
    {
        std::size_t n = num_state_words;
        base::int_mul(n, state_word_size); // Throws
        std::size_t bits_per_seed_word = 32;
        base::int_add(n, bits_per_seed_word - 1); // Throws
        n /= bits_per_seed_word;
        return n;
    }

    static constexpr std::size_t get_num_input_words(std::size_t num_seed_words)
    {
        // Ideally, we could have used `std::random_device::entropy()` as the
        // actual number of bits of entropy produced per invocation of
        // `std::random_device::operator()`, however, it is incorrectly
        // implemented on many platform. Also, it is supposed to return zero
        // when `std::random_device` is just a PRNG, but that would leave us
        // with no way to continue.
        //
        // When the actual entropy from `std::random_device` is less than
        // maximum, the seeding will be less than optimal. For example, if the
        // actual entropy is only half of the maximum, then the seeding will
        // only produce half the entropy that it ought to, but that will
        // generally still be a good seeding.
        //
        // For the (assumed) rare cases where `std::random_device` is a PRGN
        // that is not nondeterministically seeded, we include a bit of extra
        // entropy taken from such places as the current time and the ID of the
        // executing process (when available).
        //
        std::size_t n = num_seed_words;
        base::int_mul(n, 32); // Throws
        std::size_t bits_per_input_word = base::get_int_width<input_word_type>();
        base::int_add(n, bits_per_input_word - 1); // Throws
        n /= bits_per_input_word;
        base::int_add(n, num_extra_entropy_words); // Throws
        return n;
    }

    template<class F> static void seed(buffer_ref_type buffer, F func)
    {
        std::random_device rnddev; // Throws
        std::generate(buffer.begin(), buffer.end() - num_extra_entropy_words,
                      std::ref(rnddev)); // Throws
        extra_entropy_type extra_entropy;
        get_extra_entropy(extra_entropy); // Throws
        std::copy(extra_entropy.begin(), extra_entropy.end(),
                  buffer.end() - num_extra_entropy_words);
        auto seed_seq = base::SeedSeq::no_copy(buffer);
        func(seed_seq); // Throws
    }

    static void get_extra_entropy(extra_entropy_type&);
};


} // namespace detail



template<class E> inline void seed_prng_nondeterministically(E& engine)
{
    using Seeder = detail::NondeterministicRandomSeeder;
    Seeder::seed_prng(engine); // Throws
}


template<std::size_t num_seed_words, class F> inline void seed_nondeterministically(F func)
{
    using Seeder = detail::NondeterministicRandomSeeder;
    constexpr std::size_t size = Seeder::get_num_input_words(num_seed_words); // Throws
    std::array<Seeder::input_word_type, size> buffer;
    Seeder::seed(buffer, std::move(func)); // Throws
}


template<class F> inline void seed_nondeterministically_a(std::size_t num_seed_words, F func)
{
    using Seeder = detail::NondeterministicRandomSeeder;
    std::size_t size = Seeder::get_num_input_words(num_seed_words); // Throws
    base::Buffer<Seeder::input_word_type> buffer(size); // Throws
    Seeder::seed(buffer, std::move(func)); // Throws
}



// ============================ SeedSeq ============================


inline SeedSeq SeedSeq::no_copy(base::Span<const result_type> init_seed_seq) noexcept
{
    SeedSeq seq;
    seq.m_init_seed_seq = init_seed_seq;
    return seq;
}


template<class T> inline SeedSeq::SeedSeq(std::initializer_list<T> init_seed_seq) :
    SeedSeq(init_seed_seq.begin(), init_seed_seq.end()) // Throws
{
}


template<class I> inline SeedSeq::SeedSeq(I begin, I end)
{
    constexpr bool is_forward_iter =
        std::is_convertible_v<typename std::iterator_traits<I>::iterator_category,
                              std::forward_iterator_tag>;
    if constexpr (is_forward_iter) {
        init(begin, end); // Throws
    }
    else {
        std::vector<result_type> vec(begin, end); // Throws
        init(vec.begin(), vec.end()); // Throws
    }
}


template<class I> void SeedSeq::generate(I begin, I end) const
{
    static_assert(std::is_convertible_v<typename std::iterator_traits<I>::iterator_category,
                  std::random_access_iterator_tag>);

    using T = typename std::iterator_traits<I>::value_type;
    static_assert(std::is_unsigned_v<T>);
    static_assert(base::get_int_width<T>() >= 32);

    if (begin == end)
        return;

    std::fill(begin, end, T(0x8B8B8B8Bu));

    std::size_t n = std::size_t(end - begin);
    std::size_t s = m_init_seed_seq.size();
    std::size_t t = (n >= 623 ? 11 :
                     (n >=  68 ? 7 :
                      (n >=  39 ? 5 :
                       (n >=   7 ? 3 :
                        std::size_t((n - 1) / 2)))));
    std::size_t p = std::size_t((n - t) / 2);
    std::size_t q = std::size_t(p + t);
    std::size_t m = std::max(std::size_t(s + 1), n);

    auto mod = [](auto val) noexcept {
        return val & base::int_mask<std::uint_least32_t>(32);
    };

    for (std::size_t k = 0; k < m; ++k) {
        auto arg = begin[k % n] ^ begin[(k + p) % n] ^ begin[(k - 1) % n];
        auto r_1 = 1664525u * (arg ^ (mod(arg) >> 27));
        decltype(r_1 + s + m_init_seed_seq[0]) r_2;
        if (k == 0) {
            r_2 = r_1 + s;
        }
        else if (k <= s) {
            r_2 = r_1 + k % n + m_init_seed_seq[k - 1];
        }
        else {
            r_2 = r_1 + k % n;
        }
        begin[(k + p) % n] = T(mod(begin[(k + p) % n] + r_1));
        begin[(k + q) % n] = T(mod(begin[(k + q) % n] + r_2));
        begin[k % n] = T(mod(r_2));
    }

    for (std::size_t k = m; k < m + n; ++k) {
        auto arg = begin[k % n] + begin[(k + p) % n] + begin[(k - 1) % n];
        auto r_1 = 1566083941u * (arg ^ (mod(arg) >> 27));
        auto r_2 = r_1 - k % n;
        begin[(k + p) % n] = T(mod(begin[(k + p) % n] ^ r_1));
        begin[(k + q) % n] = T(mod(begin[(k + q) % n] ^ r_2));
        begin[k % n] = T(mod(r_2));
    }
}


inline std::size_t SeedSeq::size() const noexcept
{
    return m_init_seed_seq.size();
}


template<class I> inline void SeedSeq::param(I dest) const
{
    std::copy_n(m_init_seed_seq.data(), m_init_seed_seq.size(), dest); // Throws
}


template<class I> void SeedSeq::init(I begin, I end)
{
    static_assert(std::is_convertible_v<typename std::iterator_traits<I>::iterator_category,
                  std::forward_iterator_tag>);
    auto n_1 = std::distance(begin, end); // Throws
    std::size_t n_2 = 0;
    if (ARCHON_LIKELY(n_1 > 0 && base::try_int_cast(n_1, n_2))) {
        m_init_seed_seq_owner = std::make_unique<result_type[]>(n_2); // Throws
        m_init_seed_seq = { m_init_seed_seq_owner.get(), n_2 };
        return;
    }
    throw std::length_error("Initial seed sequence");
}


} // namespace archon::base

#endif // ARCHON_X_BASE_X_RANDOM_HPP
