name: Archon test suite

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test-on-ubuntu:
    name: Test on Ubuntu

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest]
        build_type: [Release, Debug]
        c_compiler: [gcc, clang]
        include:
          - c_compiler: gcc
            cpp_compiler: g++
          - c_compiler: clang
            cpp_compiler: clang++

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install clang
        sudo apt install libpng-dev libjpeg-dev libfreetype-dev libx11-dev libxi-dev libxfixes-dev libxext-dev libxrandr-dev libxrender-dev libglx-dev libgl-dev libglew-dev
        sudo apt install libxinerama-dev libxcursor-dev libxss-dev libwayland-dev wayland-protocols libdecor-0-dev libegl-dev libdrm-dev libgbm-dev libvulkan-dev libasound2-dev libpulse-dev libpipewire-0.3-dev libsndio-dev libusb-1.0-0-dev libudev-dev libxkbcommon-dev libibus-1.0-dev
        SDL_SOURCE_DIR="${{ runner.temp }}/sdl-source"
        mkdir "$SDL_SOURCE_DIR"
        git clone https://github.com/libsdl-org/SDL.git "$SDL_SOURCE_DIR"
        (cd "$SDL_SOURCE_DIR" && mkdir build && cd build && cmake .. -D CMAKE_BUILD_TYPE=Release -D SDL_X11_XTEST=OFF && make -j && sudo make install)

    - name: Checkout
      uses: actions/checkout@v6

    - name: Configure
      run: |
        cmake -S ${{ github.workspace }} -B ${{ github.workspace }}/build -D CMAKE_C_COMPILER=${{ matrix.c_compiler }} -D CMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} -D CMAKE_BUILD_TYPE=${{ matrix.build_type }} -D ARCHON_BUILD_DEMO_PROGS=YES -D ARCHON_BUILD_TEST_SUITE=YES

    - name: Build
      run: |
        cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }}

    - name: Test
      run: |
        ctest --test-dir ${{ github.workspace }}/build --build-config ${{ matrix.build_type }} --verbose

  test-on-macos:
    name: Test on macOS

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [macos-latest]
        build_type: [Release, Debug]
        c_compiler: [clang]
        include:
          - c_compiler: clang
            cpp_compiler: clang++

    steps:
    - name: Install dependencies
      run: |
        brew install libjpeg sdl3 glew

    - name: Checkout
      uses: actions/checkout@v6

    - name: Configure
      run: |
        cmake -S ${{ github.workspace }} -B ${{ github.workspace }}/build -D CMAKE_C_COMPILER=${{ matrix.c_compiler }} -D CMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} -D CMAKE_BUILD_TYPE=${{ matrix.build_type }} -D CMAKE_FIND_FRAMEWORK=LAST -D ARCHON_BUILD_DEMO_PROGS=YES -D ARCHON_BUILD_TEST_SUITE=YES

    - name: Build
      run: |
        cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }}

    - name: Test
      run: |
        ctest --test-dir ${{ github.workspace }}/build --build-config ${{ matrix.build_type }} --verbose

  test-on-windows:
    name: Test on Windows

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [windows-latest]
        build_type: [Release, Debug]
        c_compiler: [cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl

    steps:
    - name: Install dependencies
      run: |
        (cd C:\vcpkg && git pull)
        vcpkg install --triplet x64-windows libpng libjpeg-turbo freetype sdl3 glew

    - name: Checkout
      uses: actions/checkout@v6

    - name: Configure
      run: |
        cmake -S ${{ github.workspace }} -B ${{ github.workspace }}/build -D CMAKE_C_COMPILER=${{ matrix.c_compiler }} -D CMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} -D CMAKE_BUILD_TYPE=${{ matrix.build_type }} -D CMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -D ARCHON_BUILD_DEMO_PROGS=YES -D ARCHON_BUILD_TEST_SUITE=YES

    - name: Build
      run: |
        cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }}

    - name: Test
      run: |
        ctest --test-dir ${{ github.workspace }}/build --build-config ${{ matrix.build_type }} --verbose
