name: Archon test suite

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-on-ubuntu:
    name: Test on Ubuntu

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest]
        build_type: [Release, Debug]
        c_compiler: [gcc, clang-15]
        include:
          - c_compiler: gcc
            cpp_compiler: g++
          - c_compiler: clang-15
            cpp_compiler: clang++-15

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install libpng-dev libfreetype-dev libx11-dev libsdl2-dev clang-15

    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure
      run: |
        cmake -S ${{ github.workspace }} -B ${{ github.workspace }}/build -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      run: |
        cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }}

    - name: Test
      run: |
        ctest --test-dir ${{ github.workspace }}/build --build-config ${{ matrix.build_type }} --verbose

  test-on-macos:
    name: Test on macOS

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [macos-latest]
        build_type: [Release, Debug]
        c_compiler: [clang]
        include:
          - c_compiler: clang
            cpp_compiler: clang++

    steps:
    - name: Install dependencies
      run: |
        brew install libpng freetype sdl2

    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure
      run: |
        cmake -S ${{ github.workspace }} -B ${{ github.workspace }}/build -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_FIND_FRAMEWORK=LAST

    - name: Build
      run: |
        cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }}

    - name: Test
      run: |
        ctest --test-dir ${{ github.workspace }}/build --build-config ${{ matrix.build_type }} --verbose

  test-on-windows:
    name: Test on Windows

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [windows-latest]
        build_type: [Release, Debug]
        c_compiler: [cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl

    steps:
    - name: Install dependencies
      run: |
        vcpkg install --triplet x64-windows libpng freetype sdl2

    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure
      run: |
        cmake -S ${{ github.workspace }} -B ${{ github.workspace }}/build -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build
      run: |
        cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }}

    - name: Test
      run: |
        ctest --test-dir ${{ github.workspace }}/build --build-config ${{ matrix.build_type }} --verbose
